![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

my_array = np.arange(10)
print(my_array[9:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [20]:
my_matriz = np.arange(1, 21).reshape((4,5))

print(my_matriz)
print(my_matriz[::-1, ::-1])
print(my_matriz[:, -1:-3:-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 5  4]
 [10  9]
 [15 14]
 [20 19]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [21]:
print(my_matriz[0:2, 0:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [22]:
my_matriz[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [23]:
print(my_matriz[::, ::-1])
print(my_matriz[:-1:, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [9]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [10]:
np.extract(x == "Loro", x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [11]:
sec_array = np.arange(20)
print(sec_array.reshape(2,5,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [25]:
my_matriz[3::-1, 4::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [12]:
import sys
array_0s = np.full((10), 0)
print(sys.getsizeof(array_0s))
array_0s[-1] = 1
print(array_0s)

192
[0 0 0 0 0 0 0 0 0 1]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [13]:
vec = np.arange(10,50)
print(vec[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [14]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [15]:
x = np.random.randint(1, 100, [10,10])
print(x)

print(np.max(x))
print(np.min(x))

[[95 62 25 30 27 70 38 49 58 37]
 [48 13 36 81 15 49 14 96 70 60]
 [89 26 72 43 26 22 81 85 66 55]
 [75 29 22  4 25  6 46 61  3 56]
 [ 2 55 46 77  1 14 39 57  9 97]
 [39 67 66 67 71 95  5 12 84 85]
 [46 18 14 66 69 59 10 55 60 92]
 [86 74 93 57 91 53 85 24 74 57]
 [97 45 52  8 93 29  9 61 71 61]
 [63 60 57  1 37  3 38 12 56 31]]
97
1


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [16]:
vec_alt = np.random.randint(0, 100, size = (1,30))
print(np.mean(vec_alt))

47.9


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [26]:
x = np.ones((10,10))
x[1:-1:, 1:-1:] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
x = np.zeros((10,10))

x = np.zeros((10,10))
x[0:10:9] = 1
x.T[0:10:9] = 1
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [29]:
x = np.zeros((8,8), dtype = int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [30]:
x = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [36]:
matriz_alt = np.random.randint(0, 100, size = (5,5))
print(matriz_alt)

matriz_estandarizada = (matriz_alt - np.mean(matriz_alt))/np.std(matriz_alt)
print(matriz_estandarizada)


[[98 92 59 77 85]
 [34 24 18 58 60]
 [47 39 58 18  7]
 [98 63 33 14 96]
 [93 94 49 44 88]]
[[ 1.37931609  1.17324296  0.0398408   0.65806016  0.93282432]
 [-0.8187972  -1.1622524  -1.36832552  0.00549528  0.07418632]
 [-0.37230544 -0.6470696   0.00549528 -1.36832552 -1.74612624]
 [ 1.37931609  0.17722288 -0.85314272 -1.5057076   1.31062504]
 [ 1.20758848  1.241934   -0.3036144  -0.475342    1.03586088]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [43]:
mi_array = np.arange(11)

mi_array_nuevo = mi_array.copy()
mi_array_nuevo[(mi_array_nuevo >= 3) & (mi_array_nuevo <=8)] = -1
print(mi_array_nuevo)

mi_array_nuevo2 = mi_array.copy()
mi_array_nuevo2[(mi_array_nuevo2 >= 3) & (mi_array_nuevo2 <=8)] *= -1
print(mi_array_nuevo2)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [44]:
tablero = np.full(fill_value = ' ', shape = (10, 10))
tablero[0:2, 1] = 'O'
tablero[1, 3:7] = 'O'
tablero[0, 1] = 'X'
tablero[0, 0] = '-'
tablero

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [45]:
eslora = 4
import random

while True:
    orient = random.choice(['N', 'S', 'E', 'O'])

    current_pos = np.random.randint(10, size = 2)
    
    fila = current_pos[0]
    col = current_pos[1]
    
    coors_posiN = tablero[fila:fila - eslora:-1, col]
    coors_posiE = tablero[fila, col: col + eslora]
    coors_posiS = tablero[fila:fila + eslora, col]
    coors_posiO = tablero[fila, col: col - eslora:-1]
    
    if orient == 'N' and 0 <= fila - eslora < 10 and 'O' not in coors_posiN:
        tablero[fila:fila - eslora:-1, col] = 'O'
        break

    elif orient == 'E' and 0 <= col + eslora < 10 and 'O' not in coors_posiE:
        tablero[fila, col: col + eslora] = 'O'
        break

    elif orient == 'S' and 0 <= fila + eslora < 10 and 'O' not in coors_posiS:
        tablero[fila:fila + eslora, col] = 'O'
        break

    elif orient == 'O' and 0 <= col - eslora < 10 and 'O' not in coors_posiO:
        tablero[fila, col: col - eslora:-1] = 'O'
        break

    else:
        continue
tablero

array([['-', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', 'O', 'O', 'O', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [46]:
import glob

path = '/**/*.txt'
for file in glob.glob(path, recursive=True):
    print(file)

/$Recycle.Bin\S-1-5-21-4223303690-2350647594-184830190-1001\$IPYPPLX.txt
/$Recycle.Bin\S-1-5-21-4223303690-2350647594-184830190-1001\$IV8IEOG.txt
/$Recycle.Bin\S-1-5-21-4223303690-2350647594-184830190-1001\$RPYPPLX.txt
/$Recycle.Bin\S-1-5-21-4223303690-2350647594-184830190-1001\$RV8IEOG.txt
/$Recycle.Bin\S-1-5-21-4223303690-2350647594-184830190-1001\$RJLO5EI\Ejercicio_0\Entrega_0.txt
/Program Files (x86)\Hearthstone\Hearthstone_Data\Plugins\no_plugins_were_generated.txt
/Program Files (x86)\Hearthstone\Strings\esES\CREDITS_2014.txt
/Program Files (x86)\Hearthstone\Strings\esES\CREDITS_2015.txt
/Program Files (x86)\Hearthstone\Strings\esES\CREDITS_2017.txt
/Program Files (x86)\Hearthstone\Strings\esES\CREDITS_2018.txt
/Program Files (x86)\Hearthstone\Strings\esES\CREDITS_2019.txt
/Program Files (x86)\Hearthstone\Strings\esES\CREDITS_2020.txt
/Program Files (x86)\Hearthstone\Strings\esES\CREDITS_2021.txt
/Program Files (x86)\Hearthstone\Strings\esES\CREDITS_2022.txt
/Program Files (x86)\